### ISSUE TITLE
Retry logic not working properly. Performs extra retry for 2nd and next failures

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/carina-cucumber#25]
I have a feature file it has 5 scenarios as given 
Test1: Pass
Test2: Pass
Test3: Fail
Test4: Fail
Test5: Fail

When I execute a test I did the setting of retry_count=3 in config.properties. this means if any of the test fails it should retry 3 times, But this is happening only for the first scenario where as for the 2nd or next scenarios it retries one more time.
below shown execution run results: 
Test1 : Pass
Test2 : Pass

Test3 : Fail 
Test3 : Fail > Retry > 1
Test3 : Fail > Retry > 2
Test3 : Fail > Retry > 3

Test4 : Fail 
Test4 : Fail > Retry > 1
Test4 : Fail > Retry > 2
Test4 : Fail > Retry > 3
**Test4 : Fail > Retry > 4**

Test5 : Fail 
Test5 : Fail > Retry > 1
Test5 : Fail > Retry > 2
Test5 : Fail > Retry > 3
**Test5 : Fail > Retry > 4**

**Comment by vdelendik** [comment]
root cause is due to the missed DataProviderInterceptor listener. As cucumber is always dataprovider we have to enable/inject it obligatory otherwise all tests are detected as a single one and retry works for 1st failure only

**Comment by vdelendik** [comment]
fixed for execution on CI (Jenkins), cli and via IntelliJ. Issue still actual for Eclipse as DataProviderInterceptor listener is not registered/intercepted
