### ISSUE TITLE
provide independent archetype for carina-cucumber framework

### ISSUE THREAD

**Issue by vdelendik** [zebrunner/carina-cucumber#33]
as of now carina-demo and regular carina archetype already has example of the cucumber implementation. As result too common inside the classpath we have a conflicts because carina-cucumber is updated not so often. let's generate independent carina-cucumber archetype and sample project where we could track only cucumber based tests, dependencies etc

**Comment by vdelendik** [comment]
done: https://github.com/zebrunner/carina-cucumber/pull/39
also created new demo project for that: https://github.com/zebrunner/cucumber-demo

**Comment by okamara** [comment]
Verified on org. env.

**Comment by vdelendik** [comment]
invalid artifact and group id provided for new archetype... it should be fixed.

**Comment by okamara** [comment]
verified, fixed.

**Comment by vdelendik** [comment]
done
