### ISSUE TITLE
Feature and Scenario Name Value should be displayed in reports folder

### ISSUE THREAD

**Issue by prasadjshimpi** [zebrunner/carina-cucumber#43]
Earlier shown Feature and Scenario Name Value is not getting displayed.
An issue occurred in Release: 7.4.24
File name: src/main/java/com/qaprosoft/carina/core/foundation/cucumber/CucumberRunner.java 
Line no 92  : ReportContext.setCustomTestDirName(testName);

The above line should be uncommented.

**Comment by vdelendik** [comment]
ticket will be fixed in scope of #47
