### ISSUE TITLE
add opportunity to change name of the folder for scenario in reports folder

### ISSUE THREAD

**Issue by akamarouski** [zebrunner/carina-cucumber#47]
In 7.3.19 in the reports folder the name of the folder for each scenario equals the scenario name. From 7.4.21 version the name of the folder consists from udid 
Add opportunity to rename in advance before starting test.

Also add log info about name of the renaming

**Comment by vdelendik** [comment]
@akamarouski, let's introduce new config properties for carina-cucumer and do folder rename if it is true.
1. guarantee we don't fail huge suites for those to whom this feature is not important
2. provide an option to enable it for certain suites/rojects
```
custom_testdir_naming=false
```
